
//! Autogenerated weights for `pallet_zklogin`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-06-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `xuyizhengs-MBP`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zklogin
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// frame/zklogin/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_zklogin`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_zklogin::WeightInfo for WeightInfo<T> {
	/// Storage: `ZkLogin::Jwks` (r:0 w:2)
	/// Proof: `ZkLogin::Jwks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_jwks_unsigned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `6`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ZkLogin::Keys` (r:1 w:1)
	/// Proof: `ZkLogin::Keys` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1491))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ZkLogin::Jwks` (r:0 w:1)
	/// Proof: `ZkLogin::Jwks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_jwk() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
