
//! Autogenerated weights for `pallet_zklogin`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-06-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `xuyizhengs-MBP`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zklogin
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// frame/zklogin/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_zklogin`.
pub trait WeightInfo {
    fn submit_jwks_unsigned(c: u32) -> Weight;
    fn update_keys(c: u32) -> Weight;
    fn set_jwk() -> Weight;
}

/// Weight functions for `pallet_zklogin`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::AllExtrinsicsLen` (r:1 w:1)
	/// Proof: `System::AllExtrinsicsLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TransactionPayment::NextFeeMultiplier` (r:1 w:0)
	/// Proof: `TransactionPayment::NextFeeMultiplier` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ZkLogin::Jwks` (r:0 w:10)
	/// Proof: `ZkLogin::Jwks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `c` is `[0, 10]`.
	fn submit_jwks_unsigned(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `6`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(5_013_217, 0)
			.saturating_add(Weight::from_parts(0, 6))
			// Standard Error: 43_385
			.saturating_add(Weight::from_parts(8_815_659, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `ZkLogin::Keys` (r:1 w:1)
	/// Proof: `ZkLogin::Keys` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `c` is `[0, 10]`.
	fn update_keys(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_388_553, 0)
			.saturating_add(Weight::from_parts(0, 1491))
			// Standard Error: 26_967
			.saturating_add(Weight::from_parts(473_328, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ZkLogin::Jwks` (r:0 w:1)
	/// Proof: `ZkLogin::Jwks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_jwk() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
